crt = File.join(File.dirname(__FILE__), "..", "common_rake_tasks")
require File.join(crt, "rake_task_requires")

@gem_spec = Gem::Specification.new do |s|
  s.name = 'mack-pdf_writer'
  s.version = GEM_VERSION
  s.summary = %{Rendering Engine}
  s.description = %{PDF Rendering Engine for Mack Framework}
  s.author = "Darsono Sutedja"
  s.email = "darsono.sutedja@gmail.com"
  s.homepage = "http://www.mackframework.com"

  s.test_files = FileList['test/**/*']

  s.files = FileList['lib/**/*.rb', 'README', 'doc/**/*.*']
  s.add_dependency("pdf-writer", "1.1.8")
  s.require_paths << 'lib'
  
  s.has_rdoc = true
end

# Require all the necessary rake tasks:
[:install, :package, :rdoc, :release, :test].each do |t|
  load(File.join(crt, "#{t}.rake"))
end