crt = File.join(File.dirname(__FILE__), "..", "common_rake_tasks")
require File.join(crt, "rake_task_requires")

@gem_spec = Gem::Specification.new do |s|
  s.name = 'mack-mailer'
  s.version = GEM_VERSION
  s.summary = %{Mailer functionality for Mack applications.}
  s.description = %{Mailer functionality for Mack applications.}
  s.author = "Mark Bates"
  s.email = "mark@mackframework.com"
  s.homepage = "http://www.mackframework.com"

  s.test_files = FileList['test/**/*']

  s.files = FileList['lib/**/*.*', 'README', 'doc/**/*.*']
  s.require_paths << 'lib'
  s.add_dependency("tmail", "1.2.3.1")
  s.add_dependency("validatable", "1.6.7")
  
  s.has_rdoc = true
  s.rubyforge_project = "magrathea"
end

# Require all the necessary rake tasks:
[:install, :package, :rdoc, :release, :test].each do |t|
  load(File.join(crt, "#{t}.rake"))
end