crt = File.join(File.dirname(__FILE__), "..", "common_rake_tasks")
require File.join(crt, "rake_task_requires")

@gem_spec = Gem::Specification.new do |s|
  s.name = "mack-facets"
  s.version = GEM_VERSION
  s.summary = "Ruby language extensions for Mack"
  s.description = "mack-facets was developed by: markbates"
  s.author = "markbates"
  s.email = "mark@mackframework.com"
  s.homepage = "http://www.mackframework.com"

  s.test_files = FileList['test/**/*']

  s.files = FileList['lib/**/*', 'README', 'doc/**/*.*', 'bin/**/*.*']
  s.require_paths << 'lib'

  # s.add_dependency("facets", "2.4.4")
  # s.add_dependency("english", "0.2.0")
  # s.add_dependency("extlib", "0.9.8")
  s.extra_rdoc_files = ["README"]
  # s.has_rdoc = true
  s.rdoc_options << '--exclude=gems/'
  s.required_ruby_version = ">= 1.8.6"
  s.rubyforge_project = "magrathea"
end

# Require all the necessary rake tasks:
[:install, :package, :rdoc, :release, :test].each do |t|
  load(File.join(crt, "#{t}.rake"))
end

