crt = File.join(File.dirname(__FILE__), "..", "common_rake_tasks")
require File.join(crt, "rake_task_requires")

@gem_spec = Gem::Specification.new do |s|
  s.name = 'mack-distributed'
  s.version = GEM_VERSION
  s.summary = %{Distributed Application}
  s.description = %{Distributed Application Support for Mack Framework}
  s.author = "markbates"
  s.email = "mark@mackframework.com"
  s.homepage = "http://www.mackframework.com"

  s.test_files = FileList['test/**/*']

  s.bindir = "bin"
  s.executables << "mack_ring_server"
  s.files = FileList['lib/**/*', 'README', 'doc/**/*.*']
  
  # s.add_dependency("addressable", "1.0.4")
  s.add_dependency('mack-caching', GEM_VERSION)
  
  s.require_paths << 'bin'
  s.require_paths << 'lib'
  
  # s.has_rdoc = true
  s.rdoc_options << '--exclude=gems/'
  s.rubyforge_project = "magrathea"
end

# Require all the necessary rake tasks:
[:install, :package, :rdoc, :release, :test].each do |t|
  load(File.join(crt, "#{t}.rake"))
end